name: Vulnerability Report
description: Report a possible exploit vector
title: "[Vulnerability]: "
labels: ["vulnerability"]
projects: ["Nibbles-and-Mlems-Exotics-LLC/2"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise explanation of the vector.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to execute
      description: How can this exploit be carried out?
  - type: dropdown
    attributes:
      label: Platform
      description: What OS(s) are you running on?
      multiple: true
      options:
        - Windows
        - Linux (include distribution in Additional Context)
        - Mac
        - Android
        - iOS
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Any other information that could be useful.
  - type: markdown
    attributes: 
      value: |
        # Example
        Title: [Vulnerability]: Possible data exposure in logs

        Description: Individual animal health records may be exposed in the logs when the logging level is set to INFO.

        Steps to Reproduce:
          Set the logging level in Options to INFO
          Add or edit a new Health Record for an animal
          Save the record
          The logs will contain fields from the newly added record
        
        Platform: Linux

        Additional Context: Linux Mint 22.2
